### PR TITLE
Declare all token modifiers explicitly for labels and attributes

### LINKED ISSUE #96: Consider different schema representations for variable defaults (to aid highlighting `variable` name)
## Background

Currently we pre-decode variable blocks (via earlydecoder) for `type` and we use that in the 2nd (real) decoding in combination with DependentBody to inform what type `default` is:

https://github.com/hashicorp/terraform-schema/blob/faadc57bd40a52476f452a0be2ddd18bd894007e/schema/schema_merge.go#L240-L261

This has the benefit of providing more contextual/relevant help for defaults, e.g.

However the downside is that we also use the existence of `DependentBody` to inform the user of which label or attribute has "pre-set" (enum) values, which has the less desirable effect here in the variable block, as demonstrated by semantic highlighting in https://github.com/hashicorp/terraform-ls/pull/817
156360469-5de34aef-a069-4c43-85b9-ad158b0bf888

## Proposal

Explore how else we could signify the relationship between `type` and `default` which doesn't involve `DependentBody` or consider adding a flag to [`LabelSchema`](https://pkg.go.dev/github.com/hashicorp/hcl-lang@v0.0.0-20220127164523-96d2cc173e49/schema#LabelSchema) which would control whether the label should be reported as dependent. We already have `Completable` flag there for similar reasons.

### PR DESCRIPTION
**Pull request by radeksimko**
Depends on https://github.com/hashicorp/hcl-lang/pull/110
Fixes #96 

---

## Background

Admittedly this may look like a lot of work for avoiding highlighting of one particular block. I would say though that the mis-highlighting of that single label in `variable` block popped up as an effect of a suboptimal design.

The motivation here was therefore to modifiers more flexible and remove the magical behaviour where `hcl-lang` decoder would assign the dependent modifier automatically. This way it's more explicit.

### Before
Screenshot 2022-03-22 at 11 21 57

### After
Screenshot 2022-03-22 at 11 20 09

The following VS Code theme was used to produce the above examples:

```json
{
  "name": "Example Theme",
  "semanticHighlighting": true,
  "semanticTokenColors": {
    "hcl-blockLabel.hcl-dependent": {"foreground": "#FFF", "fontStyle": "bold"},
    "hcl-attrName.hcl-dependent": {"foreground": "#FFF", "fontStyle": "bold"}
  }
}
```

### CODE REVIEW

**Comment by dbanck** [comment]
Do we need to add `TokenModifierDependent` for this attributes, too? Because those have `IsDepKey: true` set?

https://github.com/hashicorp/terraform-schema/blob/23627f26a2c018773960e55a0c482b5c3b42d09f/internal/schema/0.13/terraform_block.go#L52-L56

https://github.com/hashicorp/terraform-schema/blob/23627f26a2c018773960e55a0c482b5c3b42d09f/internal/schema/0.14/terraform.go#L64-L68

https://github.com/hashicorp/terraform-schema/blob/23627f26a2c018773960e55a0c482b5c3b42d09f/internal/schema/universal/resource_block.go#L42-L49

**Comment by radeksimko** [comment]
Oh yes, of course - I missed these spots 🙈  - good catch!

**Comment by radeksimko** [comment]
@dbanck just added the missing modifiers - PTAL

**Review by dbanck — APPROVED** [review]
👍

**Pull request merged**
